### ISSUE TITLE
Timer started at 0:01 on new map, then went back to normal after the map reopened

### ISSUE THREAD

**Issue by Wain4** [GreepTheSheep/openplanet-MXRandom#103]
Timer started at 0:01 on new map, then went back to normal after the map reopened.
Tarpor VOD: https://www.twitch.tv/videos/1894946711?t=4h25m42s
Log: https://www.twitch.tv/videos/1894946711?t=4h31m50s
Not exactly related, but some more info about room updates: https://github.com/GreepTheSheep/openplanet-MXRandom/pull/99

**Comment by GreepTheSheep** [comment]
Duplicate of #88

**Comment by Wain4** [comment]
#88 is related but not duplicate imo.
#88 breaks the run unrecoverably. In today's run, we were able to continue.

**Comment by GreepTheSheep** [comment]
that's the same bug
