### ISSUE TITLE
ManiaExchange Random Map challenge not working.

### ISSUE THREAD

**Issue by PurplBlowfish** [GreepTheSheep/openplanet-MXRandom#115]
**Describe the bug**
When attempting to start the Random Map Challenge, I get a "1 script exceptions" error.

**To Reproduce**
1. Go to plugins
2. Click on tmx randomizer, random map challenge, start random map challenge
3. See error

**Expected behavior**
I expected to play the random map challenge which has worked twice before.

**Screenshots**
![image](https://github.com/GreepTheSheep/openplanet-MXRandom/assets/148804287/2a8387cb-cd01-409d-8e94-ce93b4a69bfb)

**Openplanet (please complete the following information):**
 - Version: up to date? dont know how to find this info? sorry im new to this
 - Game: TM2020

**Additional context**
as mentioned, it has worked for me in the past few days, but only twice. Love the mod and had a ton of fun the first time playing it! thanks for creating this!

**Comment by GreepTheSheep** [comment]
@EdVraz This error comes from the saving run system https://github.com/GreepTheSheep/openplanet-MXRandom/blob/ca811f90b6020a5e4af928c308d7e0c3382d2be7/src/Utils/DataManager.as#L71, since you have cooked up this, can you take a look at this error?

**Comment by PurplBlowfish** [comment]
Any luck with this? still getting the same error.

**Comment by GreepTheSheep** [comment]
> Any luck with this? still getting the same error.

As a workaround, you can delete the folder `C:\Users\%username%\OpenplanetNext\PluginStorage\MXRandom\Saves` while waiting

**Comment by EdVraz** [comment]
Sorry, I didn't have the time to get to this earlier. 

Seems like the file corrupts for some reason? I cant track it down though. I'll go ahead and make it resolve the conflict with a corrupted save file for the future and if people keep having it repeatedly they can open a new issue (but it doesn't look like this is happening frequently anyway). PR soon.
