### ISSUE TITLE
No 'scripts' tab in openplanet UI

### ISSUE THREAD

**Issue by RoundTab1er** [GreepTheSheep/openplanet-MXRandom#121]
Cannot figure out how to use the plugin. When I open trackmania there is no 'scripts' tab in the openplanet UI. Does this plugin require club access? If so, that should be clearly documented in the readme. 

1. Open trackmania
2. Open the openplanet uI
3. No scripts tab

![tm_openplanet](https://github.com/GreepTheSheep/openplanet-MXRandom/assets/7749249/1da91126-fdd2-4e62-aafa-45706c7be256)

 - Version: 1.26.9
 - Game: TM2020

**Comment by GreepTheSheep** [comment]
This issue is not related to the plugin. If you want to report Openplanet issues, go to https://github.com/Openplanet-nl/issues
