### ISSUE TITLE
Website doesn't work

### ISSUE THREAD

**Issue by platnub** [GreepTheSheep/openplanet-MXRandom#124]
**Describe the bug**
The website doesn't exist.
https://greep.gq/discord
https://www.whois.com/whois/greep.gq

**Comment by GreepTheSheep** [comment]
New domain is https://greep.fr

Discord is https://greep.fr/#/discord

**Comment by GreepTheSheep** [comment]
Where did you find the old domain ?

**Comment by platnub** [comment]
> Where did you find the old domain ?

https://openplanet.dev/plugin/mxrandom
![image](https://github.com/GreepTheSheep/openplanet-MXRandom/assets/81484914/aca9e8b1-3fa7-483d-a910-17571b8dc090)

**Comment by GreepTheSheep** [comment]
@platnub updated, thanks!
