### ISSUE TITLE
Allow filtering maps by date

### ISSUE THREAD

**Issue by davidmarcos98** [GreepTheSheep/openplanet-MXRandom#128]
Originally thought to prevent troll map mass uploads for Lars&Scrapie RMC battle challenge, some people also showed interest on having the option to filter maps based on a date interval. A use case being, for example, playing maps only before the ice update, or before the new cars were released.

The optimal solution would be to have date filtering in the mapsearch2 api endpoint, but otherwise the map upload and update dates can be checked when preloading the map, and preloading a new map if such date is not inside the desired interval.

**Comment by GeorgGa** [comment]
I just want to add a little concern: Would filtering by date still allow mappers to change the tags of a map they already uploaded some weeks ago? Or would changing the tags also alter the _update date_ information?

**Comment by davidmarcos98** [comment]
I don't know if the update date changes **in TMX** if you just modify the tags.
