### ISSUE TITLE
Both Maniaexchange and RMC arent working, it just says "insufficient permission" for both

### ISSUE THREAD

**Issue by Tuckman18school** [GreepTheSheep/openplanet-MXRandom#139]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on [GitHub](https://github.com/GreepTheSheep/openplanet-MXRandom/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of the plugin; I do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Describe the bug

```markdown
I just got Trackmania for pc and its my first time using openplanet. I download both maniaexchange and RMC and both have a red circle with a x. I go to the log, it says "insufficient permission" for both. My laptop said Trackmania was trying to access a folder but when i gave permissons for that folder it didnt fix. so i have useless plugins right now.
```

### To Reproduce

```markdown
I have no idea
```

### Expected behavior

```markdown
it to run right and let me do RMC and RMS
```

### Screenshots

```markdown
wont let me
```

### Openplanet version

1.27.2

### Plugin version

2.5.4 1.2.9

### Trackmania game edition

TMNEXT (Trackmania 2020)

**Comment by GreepTheSheep** [comment]
"insufficient permission" error means you don't have Club edition of the game since both plugins loads community maps, that aren't allowed in the Starter edition.

**Comment by Tuckman18school** [comment]
i can get them off the mania exchange website and run them so i dont see how that would be a problem

**Comment by GreepTheSheep** [comment]
Would like to see how you manage to run that
