### ISSUE TITLE
Game not responding after attempting to search while paused

### ISSUE THREAD

**Issue by FrostyBeep** [GreepTheSheep/openplanet-MXRandom#46]
When in the pause screen (Resume, Give Up, Exit menu) and pressing the "Start searching" button, the game will stop responding.
I'm not using the challenge timer, but simply the random map picker. The top bar options with keyboard bindings and such will remain functional, but the game itself is frozen.

I've tried reloading openplanet scripts, both with the "restart script engine" menu option and by manually stopping and starting the scripts. Nothing seems to fix the hang besides restarting TM2020.

**Comment by FrostyBeep** [comment]
I don't know if my log file will help, but I've saved it here. I think. I dunno.
It probably won't help much, It looks like everything's working just fine there. I can replicate the issue just fine if needed.
[Openplanet.log](https://github.com/GreepTheSheep/openplanet-mx-random/files/7998575/Openplanet.log)

**Comment by GreepTheSheep** [comment]
I had already had reports about this and had used the fix from Glocom on the "Speedrun map switcher" plugin. It doesn't seem to work all the time. I'll look into it (and try to talk to Glocom about it too)

**Comment by GreepTheSheep** [comment]
Fixed in https://github.com/GreepTheSheep/openplanet-mx-random/commit/4114fc1489890e69e320921dd5ea0939ece361a2

**Comment by FrostyBeep** [comment]
Unfortunately it seems to not be fixed, but it might just be some nonsense with loading maps while in the pause screen.

**Comment by lostpebble** [comment]
Yea running into this a lot lately. I have a habit of pressing the escape key when I want to give up, and then clicking the next button... but it locks me out of the game and no maps load. Have to quit the game completely.

I just need to remember to not do it- but its happened a couple times now and its very frustrating.

**Comment by mrdarrengriffin** [comment]
Bump, this is so frustrating. I can't play RMC or "Quick Play" without the game not responding

**Comment by GreepTheSheep** [comment]
I'll add a security that disable the button if you open the pause menu asap

**Comment by XertroV** [comment]
The fix for this is to pass `::Quit` not `::Resume` when in the menu.

example: https://github.com/XertroV/tm-cgf-library/blob/6a1da6ae57bd62cee90c3936e29d1d590461fc07/src/Maps.as#L33

**Comment by GreepTheSheep** [comment]
not a bad idea, will keep it aside
