### ISSUE TITLE
TMX Performance Issues due to Length Filter

### ISSUE THREAD

**Issue by RikuXan** [GreepTheSheep/openplanet-MXRandom#68]
Recently it seems like many people have complained about TMX's API performance causing RMX runs to hang without being able to load the next map. I would guess that the recently added preloading feature will help a lot in this regard, but I found another interesting detail which might help creating a fix or workaround.

If I'm not mistaken, the API call made during a TM2020 run is `https://trackmania.exchange/mapsearch2/search?api=on&random=1&etags=23,37,40&vehicles=1&mtype=TM_Race&lengthop=1&length=9`. Trying it out in my browser, the response either takes a very long time, or even times out completely. Removing the `lengthop` and `length` parameters or configuring them for a smaller range (e.g. 1 & 8) greatly reduces response latency for me. Curiously, even using `lengthop=3&length=8` which should functionally be the same (<9 vs <=8) improves latencies significantly for me.

I have no idea why this exact combination of parameters leads to slowdowns (maybe it also isn't special in any way and the cause is that it's the default parameter set used by the plugin and therefore many people), but playing around with the parameters might alleviate some of the issues (e.g. using the abovementioned 3 & 8). While I do not know how the TMX backend looks like, I would guess there is a chance that it is not purely a load issue but also some kind of configuration problem (e.g. missing/corrupted indices or stuff like that). From what I understood, you are acquainted with some of the people at TMX, so maybe this information can help the troubleshooting on their side.

**Comment by RikuXan** [comment]
I don't think it is really browser-dependent, I can reproduce the differences without a browser just in my terminal.  
I ran two looped curl commands in parallel, one with the 1 & 9 parameters and the other one with the 3 & 8 set (could have also removed the parameters here completely, but even with them the difference is very apparent).

The results are as follows [HTTP Status Code, Total Request Time (s)]:

```
1 & 9              3 & 8            
200,1.206497       200,0.228672     
500,32.697555      200,0.220302     
500,32.930335      200,0.216092     
200,29.322438      200,0.202863     
200,20.363323      200,0.204545     
200,28.006729      200,0.255433     
500,32.710936      200,0.206176     
500,32.760310      200,0.231940     
500,32.761995      200,2.353784     
500,32.772244      200,0.530688     
500,32.774126      200,0.199599     
500,32.800077      200,0.221017     
500,32.805488      200,0.269056     
500,32.813109      200,0.263094     
500,32.825916      200,0.236149     
500,32.841230      200,0.219799     
500,32.915155      200,0.222660     
500,32.932253      200,0.203050     
500,32.936464      200,0.380862     
500,32.955481      200,0.381692     
```

Most of the the requests for the default parameter set seem to time out (although I might have tried at a particularly bad time, I think it's usually not as extreme as here), whereas the alternative parameters consistently provide sub-second responses for me.

**Comment by EdVraz** [comment]
> I don't think it is really browser-dependent, I can reproduce the differences without a browser just in my terminal. I ran two looped curl commands in parallel, one with the 1 & 9 parameters and the other one with the 3 & 8 set (could have also removed the parameters here completely, but even with them the difference is very apparent).
> 
> The results are as follows [HTTP Status Code, Total Request Time (s)]:
> 
> ```
> 1 & 9              3 & 8            
> 200,1.206497       200,0.228672     
> 500,32.697555      200,0.220302     
> 500,32.930335      200,0.216092     
> 200,29.322438      200,0.202863     
> 200,20.363323      200,0.204545     
> 200,28.006729      200,0.255433     
> 500,32.710936      200,0.206176     
> 500,32.760310      200,0.231940     
> 500,32.761995      200,2.353784     
> 500,32.772244      200,0.530688     
> 500,32.774126      200,0.199599     
> 500,32.800077      200,0.221017     
> 500,32.805488      200,0.269056     
> 500,32.813109      200,0.263094     
> 500,32.825916      200,0.236149     
> 500,32.841230      200,0.219799     
> 500,32.915155      200,0.222660     
> 500,32.932253      200,0.203050     
> 500,32.936464      200,0.380862     
> 500,32.955481      200,0.381692     
> ```
> 
> Most of the the requests for the default parameter set seem to time out (although I might have tried at a particularly bad time, I think it's usually not as extreme as here), whereas the alternative parameters consistently provide sub-second responses for me.

Interesting. curl shows similar behaviour for me.
I'm curious why firefox doesn't have this issue tho

**Comment by RikuXan** [comment]
Are you sure it's always better in FF and you didn't just hit a lucky timeframe where the API for whatever reason was faster?  
For me, the behaviour is the same in FF as in Edge or curl, although there could obviously be something about your specific FF setup that makes a difference.

**Comment by EdVraz** [comment]
> Are you sure it's always better in FF and you didn't just hit a lucky timeframe where the API for whatever reason was faster? For me, the behaviour is the same in FF as in Edge or curl, although there could obviously be something about your specific FF setup that makes a difference.

Yes, the requests with 1 and 9 are almost always slow in curl/chrome, some might be faster but if I refresh in chrome its almost every time noticably slow.

on FF on the other hand it's just always quick when I refresh.

But probably the simplest solution will just be to just change the parameters and then don't bother with it again.

**Comment by GreepTheSheep** [comment]
for this commit https://github.com/GreepTheSheep/openplanet-MXRandom/commit/1229590dfe038efe69d39ccdca9f61f813a90eed, I changed operators from 1 & 9 to 3 & 8 to just see if it can improves. Try testing on your end if it's improved

**Comment by RikuXan** [comment]
I've been trying to check a few times the last days to see if there was a difference, but "unfortunately" it seems that the TMX API didnt't have any issues with either parameter set whenever I checked. Maybe the guys at TMX also fixed the issue on their side, but either way, as long as the new parameter set doesn't decrease in performance it should be fine.

**Comment by GreepTheSheep** [comment]
Ok that's good I believe, will close the issue.

**Comment by GreepTheSheep** [comment]
> Spammiej had a performance issue with loading the next map. https://www.twitch.tv/videos/1823863161?t=1h33m31s

@EdVraz Can you try now with 3 & 8 what are response times and try to compare with 1 & 9.

I thought about moving the link to a config so I can edit easily without making updates

**Comment by EdVraz** [comment]
> > Spammiej had a performance issue with loading the next map. https://www.twitch.tv/videos/1823863161?t=1h33m31s
> 
> @EdVraz Can you try now with 3 & 8 what are response times and try to compare with 1 & 9.
> 
> I thought about moving the link to a config so I can edit easily without making updates

on my end it appears to show the opposite behaviour as before now, 3&8 being slow and timing out whereas 1%9 gives instant responses.

**Comment by RikuXan** [comment]
Yeah, trying the requests right now, it's exactly the opposite as before: the 3/8 request times out while the 1/9 request works quickly. So the issue is not a specific set of parameters, but rather the same set of parameters being used by a large enough number of people (I'd guess by now enough people have upgraded their plugin version).

I have no idea what dark magic inside the TMX backend leads to two functionally equal requests showing such a performance disparity, but it looks very much like some kind of configuration issue to me: the fact that one set of parameters still works fine while the other one times out precludes it from being a pure load problem for me.

The last workaround that I can think of without working together with the TMX guys would be removing the length filter from the request completely and post-filtering the map length in the application. But seeing how strange the behavior is, I wouldn't even bet on that working, depending on what the exact issue is, this might just slow down the non-filtered request after enough people use it.

**Comment by Wain4** [comment]
> The last workaround that I can think of, without working together with the TMX guys, would be removing the length filter from the request completely and post-filtering the map length in the application. But seeing how strange the behavior is, I wouldn't even bet on that working, depending on what the exact issue is, this might just slow down the non-filtered request after enough people use it.

I would bet on that working fine, because that's exactly the request used by bingo.

**Comment by EdVraz** [comment]
> I would bet on that working fine, because that's exactly the request used by bingo.

gonna implement this then and see what happens.

**Comment by EdVraz** [comment]
Does anyone know for what length "9" (and all the other lengths) actually stand? I can't find anything on that

**Comment by Wain4** [comment]
> Does anyone know for what length "9" (and all the other lengths) actually stand? I can't find anything on that

"9" means 3 minutes, you can see it as a dropdown on the TMX website. There's a "more filters" button that lets you enable the length and lengthop filters.
https://trackmania.exchange/mapsearch2?length=9&lengthop=1

**Comment by EdVraz** [comment]
> > Does anyone know for what length "9" (and all the other lengths) actually stand? I can't find anything on that
> 
> "9" means 3 minutes, you can see it as a dropdown on the TMX website. There's a "more filters" button that lets you enable the length and lengthop filters. https://trackmania.exchange/mapsearch2?length=9&lengthop=1

Ah, I was looking at the API documentation, ty!

**Comment by Wain4** [comment]
Nevermind. Geekid posted in Discord:
> bingo uses the same mapsearch endpoint as RMC, only with slightly different query filters. I've defenitely noticed over time with the TMX api that reusing the same endpoint tends to make the server block that endpoint entirely or respond slower. Changing query parameters has a drastic effect on reliability and I think it would be more reliable for RMC in case of a failure to try moving or changing some parameters which could make it work better.

> also, i'm sure how bingo can be seen as more reliable than RMC, there's frequently bingo outages due to TMX not being available, but I guess that since the maps are loaded at game start and you can't have any other problems with maps during the game after that, it is seen as more reliable 😄

**Comment by EdVraz** [comment]
> Nevermind. Geekid posted in Discord:

Hmm. I'm still going to go ahead with adding the change, if we're lucky it resolves the issues with timing out that occur, and if not we gain some extra knowledge, which... can't hurt I guess. Also, it adds an additional variable, so instead of 1&9 or 3&8 we also have no parameters at all now.

**Comment by EdVraz** [comment]
I'll go ahead and add something for dynamic switching of query params too though. Might help too

**Comment by EdVraz** [comment]
I'll go ahead and add something for dynamic switching of query params too though. Might help too

**Comment by Wain4** [comment]
The "length" of a map is a thing that the uploader can select on TMX, it doesn't have to match the author time. Checking the AT would be a change to RMC rules.

**Comment by EdVraz** [comment]
> The "length" of a map is a thing that the uploader can select on TMX, it doesn't have to match the author time. Checking the AT would be a change to RMC rules.

Oh I didn't realise that. I'm gonna change that. But only for RMS, the RMC rules allow you to skip any AT longer than 3 minutes, so it should be fine to just cut off there.

**Comment by Wain4** [comment]
Yeah, best to not check AT in RMC either since RMC rules say you're allowed to skip, but not required to skip (if the AT is longer than 3 minutes).

**Comment by ozontm** [comment]
Thank you everyone for your input.

I have pushed a little update that might have resolved the issue.

**Comment by EdVraz** [comment]
At the moment it does not seem to function no matter what parameters you use, seems it got worse in some way?

**Comment by ozontm** [comment]
> At the moment it does not seem to function no matter what parameters you use, seems it got worse in some way?

Yes, I could replicate it today, too. Pushed another fix.

**Comment by ozontm** [comment]
We note the issue still persists (albeit in another form). While the RMC queries run fine now, no matter if logged in or out, we do now experienced increased page outage.

We have identified another potential source that could have caused it. Due to time contraints from our side + the outages happening at random times, it's hard to predict when this issue is resolved. We're working on it, though.
