### ISSUE TITLE
Web leaderboard

### ISSUE THREAD

**Issue by The-Code-Monkey** [GreepTheSheep/openplanet-MXRandom#69]
I made a website that currently shows the leaderboards for RMC and RMS. Is it possible that when a run finishes in the app you could call an api to get the current record for the gamemode they are playing and if they have more AT's than the current record then you could hit another of the apis to add the new record to the leaderboards?

**Comment by The-Code-Monkey** [comment]
Yeah that's fine with me, let me know if you need any help with the actual API. But yeah happy to keep the web interface going.

**Comment by GreepTheSheep** [comment]
I've paused this because I'm actually focusing on RMT.
Better wait at the moment :)

**Comment by Flink91** [comment]
If you two get something to work, go ahead. I wanted to work on this but am so busy IRL...

**Comment by The-Code-Monkey** [comment]
I do have a kinda api against my DB, I have been manually adding currently but i could open up an endpoint to post data to?

Unfortunately I couldn't add it into the plugin as I don't know the language.

Let me know.

Also @Flink91 no worries. life comes first always

**Comment by GreepTheSheep** [comment]
Hey @The-Code-Monkey, i'm kinda busy with work atm 😅

It is possible to move into Discord since we'll talk about sensitive infos about player authentication and some more infos.

Here's my Discord server to join https://greep.fr/#/discord, then you can DM me on it.

Thanks :)
