### ISSUE TITLE
RMT crashes if "recently played" list is empty

### ISSUE THREAD

**Issue by Wain4** [GreepTheSheep/openplanet-MXRandom#75]
"Script exception: Index out of range in json array!"
https://github.com/GreepTheSheep/openplanet-MXRandom/blob/433b3ebbfa96abf681e86ca41e699d2b7bd4f440/src/Utils/RMC/RMT.as#LL412C42-L412C42
Log is visible at https://www.twitch.tv/videos/1828205532?t=1h14m31s

**Comment by GreepTheSheep** [comment]
Already fixed in https://github.com/GreepTheSheep/openplanet-MXRandom/commit/384b7039b4596eb0d54f2e45b6541862fb188402

Check #71
