### ISSUE TITLE
Players got medals but plugin didn't show it

### ISSUE THREAD

**Issue by Wain4** [GreepTheSheep/openplanet-MXRandom#81]
RMT was started with custom search parameters. First map worked and was gold skipped. On the second map, someone got gold but the plugin didn't show an option to gold skip, then someone got AT and the plugin didn't show that either.

**Comment by GreepTheSheep** [comment]
There's not enough details for this issue, is there any logs, any more details ?

**Comment by EdVraz** [comment]
by the description alone I cannot reproduce it, works fine for me and I can gold skip the second map

**Comment by Wain4** [comment]
VOD: https://www.twitch.tv/videos/1835944129?t=4h37m22s
Log isn't shown, sorry

**Comment by Wain4** [comment]
Here's a VOD where a gold medal worked, but the AT on the same map didn't work. Streamer took gold and skipped to next map, and medals didn't work on that map. https://www.twitch.tv/videos/1843947315?t=3h42m47s

**Comment by GreepTheSheep** [comment]
Moved to #89 (more details on this issue)
