### ISSUE TITLE
RMT null pointer access on collecting goal medal after medal below goal was collected

### ISSUE THREAD

**Issue by dwhitacre** [GreepTheSheep/openplanet-MXRandom#89]
**Describe the bug**
During this RMT run someone on the server got the gold medal and then 2 minutes later the author (goal) medal was obtained. When the author medal was obtained a null pointer access was thrown leading to the plugin not correctly switching maps.

**To Reproduce**
Seems to be caused by someone getting gold and then author medal happening later. It was on a prepatch ice map as well.
- Gold medal obtained here by someone in lobby: https://www.twitch.tv/videos/1851520438?t=02h54m51s
- Author medal obtained here by the host: https://www.twitch.tv/videos/1851520438?t=02h57m32s

**Expected behavior**
I expect the map to successfully switch and no null pointer access to log

**Screenshots**
Relevant Logs:
- version
```
[   ScriptRuntime] [00:37:31] [MXRandom]  Plugin was updated, old version was "2.3.3"
```
- window of issue
```
[   ScriptRuntime] [04:34:12] [MXRandom]  RMT: Fetching a random map...
[   ScriptRuntime] [04:34:12] [MXRandom]  Get: https://trackmania.exchange/mapsearch2/search?api=on&random=1&etags=23,37,40&lengthop=1&length=9&vehicles=1&mtype=TM_Race
[   ScriptRuntime] [04:34:32] [MXRandom]  RMT: Next Random map: Burn Up The Ice (3018)
[   ScriptRuntime] [04:36:08] [MXRandom]  Teuty got below goal medal with a time of 45533
[   ScriptRuntime] [04:37:50] [MXRandom]  AR_Down got goal medal with a time of 42564
[   ScriptRuntime] [04:37:50] [MXRandom]  RMT: Random map: Burn Up The Ice (3018)
[   ScriptRuntime] [04:37:50] [MXRandom]  Saving JSON file
[   ScriptRuntime] [04:38:43] [MXRandom]  RMT: Fetching a random map...
[   ScriptRuntime] [04:38:43] [MXRandom]  Get: https://trackmania.exchange/mapsearch2/search?api=on&random=1&etags=23,37,40&lengthop=1&length=9&vehicles=1&mtype=TM_Race
[   ScriptRuntime] [04:38:47] [MXRandom]  RMT: Next Random map: Kleenotripartie (19706)
[   ScriptRuntime] [04:39:18] [MXRandom]  el_pent got below goal medal with a time of 34306
[   ScriptRuntime] [04:41:26] [MXRandom]  Script exception: Null pointer access
[   ScriptRuntime] [04:41:26] [MXRandom]    MXRandom.op/:/src/Utils/RMC/RMT.as (line 556, column 13)
[   ScriptRuntime] [04:41:26] [MXRandom]      #0  PBTime@[] RMT::GetPlayersPBsMLFeed() (MXRandom.op/:/src/Utils/RMC/RMT.as line 556)
[   ScriptRuntime] [04:41:26] [MXRandom]      #1  void RMT::UpdateRecords() (MXRandom.op/:/src/Utils/RMC/RMT.as line 525)
[   ScriptRuntime] [04:41:26] [MXRandom]      #2  void RMT::UpdateRecordsLoop() (MXRandom.op/:/src/Utils/RMC/RMT.as line 583)
[   ScriptRuntime] [04:42:27] [MXRandom]  RMT: Random map: Kleenotripartie (19706)
[   ScriptRuntime] [04:42:27] [MXRandom]  Saving JSON file
[   ScriptRuntime] [04:43:30] [MXRandom]  RMT: Fetching a random map...
[   ScriptRuntime] [04:43:30] [MXRandom]  Get: https://trackmania.exchange/mapsearch2/search?api=on&random=1&etags=23,37,40&lengthop=1&length=9&vehicles=1&mtype=TM_Race
[   ScriptRuntime] [04:44:01] [MXRandom]  ManiaExchange API returned an error, retrying...
```

**Openplanet (please complete the following information):**
 - Version: 1.25.43
 - Game: TM2020

**Additional context**
It seems api calls to mx start to fail after the event as well. Manually skipping maps would successfully connect to the api and download the next map. This was used for the rest of the vod to manually skip maps after author medal was collected. Seemed to never recover from the null pointer access issue.

**Comment by dwhitacre** [comment]
```
[    ScriptEngine] [00:37:30]  Loaded zipped plugin 'MXRandom' (version 2.3.4)
```
Seems was on `2.3.4` from what I can tell.

**Comment by GreepTheSheep** [comment]
Seems like it's the same as #81. But this issue has more details. Closing #81 for using this one.

**Comment by XertroV** [comment]
I believe this happened when: 

- a player recently joined the game
- that player had no CPs yet (BestRaceTimes becomes populated after this I think)
- the check for ATs tries to access BestRaceTimes

I guess this probably happens shortly after the player joins, but not sure exactly.

Anyway, I have pushed a patch for MLFeed that should mean BestRaceTimes is always populated.
