### ISSUE TITLE
RMC can get permanently out of sync with the map

### ISSUE THREAD

**Issue by XertroV** [GreepTheSheep/openplanet-MXRandom#91]
The plugin can get out of sync with itself so it always loads the wrong map. 

**To Reproduce**
1. start RMC
2. skip map 
3. 'force switch' during loading screen
4. maybe do that a few times
5. you then get the 'actual map is not the same that we got'
6. clicking 'change map' will request a new map from TMX but what *should* have been the prior map gets loaded instead

e.g., RMC wants map A to be loaded, but it's some other map. clicking change map requests a new map B and loads map A. since B is the expected map, RMC thinks it's not working and asks you to change the map again.

**Expected behavior**

obvious

**Screenshots**

![image](https://github.com/GreepTheSheep/openplanet-MXRandom/assets/1046448/5c311a49-7a39-49df-a7f3-e3f851960059)

**Openplanet (please complete the following information):**
 - 1.25.45
 - Game: TM2020

**Additional context**
Using my api; base url is `https://map-montior.xk.io` -- it's much faster than TMX so maybe that's why

**Comment by GreepTheSheep** [comment]
Yeah this bug was known since the beginning of this button. I'll maybe try adding a condition to disable this button when the game loads a map.
