### ISSUE TITLE
add ability to save/load IP run for rmc/s/t

### ISSUE THREAD

**Issue by dwhitacre** [GreepTheSheep/openplanet-MXRandom#93]
**Is your feature request related to a problem? Please describe.**
The plugin ends up in a bad state that prevents switching map.
The tmx api goes down.
The game crashes.
etc

**Describe the solution you'd like**
It would be nice if unexpected issues are happening, I could save the IP run and then come back to it later. This doesnt necessarily need to be a manual save either, it could just be an autosave when I finish a map of my current state. Then the UI could allow to load a previous run and continue it as if the problem never happened.

**Describe alternatives you've considered**
Manual vs Autosaving - what are the pros and cons of each? Id prefer a rolling backup that autosaved for unexpected issues to be the most reliable... but you could get by with a manual save in most scenarios.

Concerns around manipulation - sure, but i think ultimately video proof is required atm, so anybody faking times or medal counts would be verifiable. i think ultimately, any tracking of that data should ultimately be done server side for leaderboard automation.

**Additional context**
Just another alternative really when trackmania is being bad. I'd be willing to work on this, maybe later this week.

**Comment by EdVraz** [comment]
I'm gonna give this a try

**Comment by dwhitacre** [comment]
@EdVraz nice work on this 🥳
