### ISSUE TITLE
The "vote skip" workaround should be even more visible

### ISSUE THREAD

**Issue by Wain4** [GreepTheSheep/openplanet-MXRandom#94]
The fix for #83 introduced a red textbox in the top left of the screen after a map is found, telling you to vote skip if switching maps takes too long. I see streamers still having trouble with this.

The red box looks like an error message. I'd expect the instructions to be displayed inside the RMT window.

The RMT window used to show the next map's name once it was found, but it doesn't anymore. The map name made it easy to see if we're waiting for a vote skip (new map found) or waiting for TMX API (no new map found). The only remaining indication of whether a map was found is the temporary red textbox.

The text mentions waiting 10 seconds, is there a reason for this? After a map is found, I've always seen it either switch instantly or get stuck completely, I've never seen it switch after 5 seconds.

**Comment by GreepTheSheep** [comment]
> The red box looks like an error message.

Changing the color can helps, noted.

> I'd expect the instructions to be displayed inside the RMT window.

Already added: the "hover for infos" message shows the same message as the notification.

> The RMT window used to show the next map's name once it was found, but it doesn't anymore.

Was a bug. On RMC/RMS the next map name is not showed until the player enter in the map in question.

> The text mentions waiting 10 seconds, is there a reason for this?

10 seconds is a prevent measure. And better waiting some more time (in any case the timer is paused between 2 maps)

---

Will keeping the issue open only for changing the color of the notification

**Comment by Wain4** [comment]
Can you also make the notification stay permanently or repeat periodically?
I think that and a different color would be enough.

**Comment by GreepTheSheep** [comment]
The notification shows only when loading/changing a map on RMT only

**Comment by Wain4** [comment]
But can it stay for as long as the map is changing?

Some people will only start reading notifications after they notice that nothing is happening for 10+ seconds. It's a problem if the notification is then already gone.

**Comment by GreepTheSheep** [comment]
ok i'll make the notification message more longer

**Comment by Wain4** [comment]
> Already added: the "hover for infos" message shows the same message as the notification.

The "hover" message should appear at the same time as the notification. Currently it appears before the notification, so before TMX has returned a map.
