### ISSUE TITLE
RMT doesn't get the next map (and it's not a TMX API issue)

### ISSUE THREAD

**Issue by Wain4** [GreepTheSheep/openplanet-MXRandom#97]
After getting an AT, the map didn't switch, but there was also no "TMX API timeout" message (which usually appears every 30 seconds if TMX can't supply a map). The next map didn't appear in the server's list of maps.
VOD: https://www.twitch.tv/videos/1867696072?t=3h22m18s

**Comment by GreepTheSheep** [comment]
There's no logs or anything, so I can't help with that
